version: 2
jobs:
  dockerbuild:
    machine: true
    steps:
      - checkout
      - run:
          name: install aws
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: Build and push Docker image
          command: |
            CIRCLE_PROJECT_REPONAME=trash
            CIRCLE_BRANCH=master
            if [[ true ]]; then
              curl --user ${CIRCLE_API_USER_TOKEN}: \
                --data 'build_parameters[CIRCLE_JOB]=terraform-release' \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            fi
workflows:
  version: 2
  buil&push:
    jobs:
      - dockerbuild:
          filters:
            branches:
              only: master
