version: 2
jobs:
  dockerbuild:
    machine: true
    steps:
      - checkout
      - run:
          name: install aws
          command: |
            sudo apt update
            sudo apt-get install -y awscli
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --region $REGION --no-include-email)
      - run:
          name: Build and push Docker image
          command: |
            sha=$CIRCLE_SHA1
            TAG=latest
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/chat:latest .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/chat:$TAG
  deployecs:
    machine: true
    steps:
      - run:
          name: install aws & ecs-deploy
          command: |
            sudo apt update
            sudo apt-get install -y awscli
            sudo wget "https://raw.githubusercontent.com/silinternational/ecs-deploy/develop/ecs-deploy" -O /usr/local/bin/ecs-deploy
            sudo chmod +x /usr/local/bin/ecs-deploy
      - run:
          name: deploying to ECS
          command: |
            sha=$CIRCLE_SHA1
            TAG=latest
            echo "ecs-deploy --region $REGION --cluster $CLUSTER --service-name $SERVICE --image $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/chat-demo:$TAG --timeout 1800"
            ecs-deploy --region $REGION --cluster $CLUSTER --service-name $SERVICE --image $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/chat-demo:$TAG --timeout 1800
workflows:
  version: 2
  buil&push:
    jobs:
      - dockerbuild:
          filters:
            branches:
              only: master
      - deployecs:
          requires:
            - dockerbuild
          filters:
            branches:
              only: master
